GET http://localhost:3000/api/v1/cliente/
###
GET http://localhost:3000/api/v1/cliente?entidadeID=A56CA66F-54DB-4953-88FE-47C8C7D653B3
###
GET http://localhost:3000/api/v1/entidade?id=fafb8b2a-d1eb-485c-a18d-3a331359a654
###
GET http://localhost:3000/api/v1/auth?username=emirian.pinto&password=00017
###
GET http://localhost:3000/api/v1/produto?entidadeID=fafb8b2a-d1eb-485c-a18d-3a331359a654
###
GET http://localhost:3000/api/v1/produto/barcode?barcode=0009668
###
GET http://localhost:3000/api/v1/produto/nome/Refeição/fafb8b2a-d1eb-485c-a18d-3a331359a654
###
GET http://localhost:3000/api/v1/vendas
###
POST http://localhost:3000/api/v1/venda/
Content-Type: application/json

{
  "Entidade_ID": "entidade123",
  "UTILIZADOR": "usuario456",
  "Itens_Comprados": [
    {
      "descricao": "Produto A",
      "quantidade": 2,
      "preco": 50
    },
    {
      "descricao": "Produto B",
      "quantidade": 1,
      "preco": 30
    }
  ],
  "Valor_Total": 130.00,
  "Data_Venda": "2024-08-08T12:00:00Z"
}
###
POST http://localhost:3000/api/v1/cliente/
Content-Type: application/json

{ "IND_COLETIVO":"S",
  "DESIG":"David",
  "DESCR":"INDIVIDIO DAVID",
  "NIF":154458805,
  "EMAIL":"da33.veiga@gmail.com",
  "TELEFONE":9996293,
  "Entidade_ID":"fafb8b2a-d1eb-485c-a18d-3a331359a654"
}
###
GET http://localhost:3000/api/v1/produto/categoria?categoriaID=04076833-c005-297b-2970-d6e25aaa8af2
###
GET http://localhost:3000/api/v1/categoria/A56CA66F-54DB-4953-88FE-47C8C7D653B3
###
GET http://localhost:3000/api/v1/venda/entidade?id=A56CA66F-54DB-4953-88FE-47C8C7D653B3
###
GET http://localhost:3000/api/v1/venda/
###
DELETE http://localhost:3000/api/v1/cliente/000189f4-f5b1-a5c0-65b4-90b1b4b0fd56/A56CA66F-54DB-4953-88FE-47C8C7D653B3
